{{- define "sa-base" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
{{- end }}

{{- if .Values.workflow.serviceAccount.create -}}
  {{- if .Values.workflow.namespaces -}}

    {{ $namespaces := .Values.workflow.namespaces }}
    {{- range $namespaces }}
      {{ $namespace := . }}
      {{ include "sa-base" . }}
  name: {{ $.Values.workflow.serviceAccount.name }}
  namespace: {{ $namespace }}
  annotations:
    {{- toYaml $.Values.workflow.serviceAccount.annotations | nindent 4 }}
    {{- end }}

  {{- else }}

    {{ include "sa-base" . }}
  name: {{ .Values.workflow.serviceAccount.name }}
    {{- if $.Values.workflow.namespace }}
  namespace: {{ $.Values.workflow.namespace }}
    {{- end }}
  annotations:
    {{- toYaml .Values.workflow.serviceAccount.annotations | nindent 4 }}

  {{- end }}
{{- end }}
