{{- define "workflow-role-base" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
{{- end }}

{{- define "workflow-role-rules" }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
{{- end }}

{{- if .Values.workflow.rbac.create -}}

  {{- if .Values.workflow.namespaces }}
    {{- range .Values.workflow.namespaces}}
      {{ $namespace := . }}
      {{- include "workflow-role-base" . }}
  name: {{ $.Release.Name }}-workflow
  namespace: {{ $namespace }}
      {{- include "workflow-role-rules" . }}
    {{- end }}

  {{- else }}
    {{- include "workflow-role-base" . }}
  name: {{ .Release.Name }}-workflow
    {{- if .Values.workflow.namespace }}
  namespace: {{ .Values.workflow.namespace }}
    {{- end }}
    {{- include "workflow-role-rules" . }}
  {{- end }}

{{- end }}
