{{- define "sa-template" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
{{- end }}

{{- if .Values.workflow.serviceAccount.create -}}
  {{- if .Values.workflow.namespaces -}}
    {{ $namespaces := .Values.workflow.namespaces }}
    {{- range $namespaces }}
      {{ $namespace := . }}
      {{ include "sa-template" . }}
  name: {{ $.Values.workflow.serviceAccount.name }}
  namespace: {{ $namespace }}
  annotations:
    {{- toYaml $.Values.workflow.serviceAccount.annotations | nindent 4 }}
    {{- end }}

  {{- else if .Values.workflow.namespace }}
    {{ $namespace := .Values.workflow.namespace }}
    {{ include "sa-template" . }}
  name: {{ $.Values.workflow.serviceAccount.name }}
  namespace: {{ $namespace }}
  annotations:
    {{- toYaml $.Values.workflow.serviceAccount.annotations | nindent 4 }}

  {{- else }}
    {{ include "sa-template" . }}
  name: {{ $.Values.workflow.serviceAccount.name }}
  annotations:
    {{- toYaml $.Values.workflow.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
